src/digitalmarket/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from checkout.views import CheckoutAjaxView ,CheckoutTestView
from dashboard.views import DashBoardView
from products.views import UserLibraryListView

urlpatterns = [
    url(r'^$', DashBoardView.as_view(), name="dashboard"),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name="checkout"),
    url(r'^test/$', CheckoutTestView.as_view(), name="test"),
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('products.urls', namespace="products")),
    url(r'^seller/', include('sellers.urls', namespace="sellers"), name="sellers"),
    url(r'^tag/', include('tags.urls', namespace="tags")),
    url(r'^library/', UserLibraryListView.as_view(), name="library")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tags/urls.py
from django.conf.urls import url

from .views import (
    TagListView,
    TagDetailView
    )

app_name = 'tags'
urlpatterns = [
    url(r'^detail/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
    url(r'^list/$', TagListView.as_view(), name='list'),
]

src/base/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <!--JQuery-->
    <!--Nota: toda vez que adicionar arquivo em static/ rodar "python manage.py collectstatic" pra
        atualizar com a pasta static_cdn -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.12.2.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script src="{% static 'js/django.csrf.js' %}"></script>
     <!--===========-->
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <style>
        .main-content{
            width: 800px;
            margin: 0 auto;
            clear: both;
        }
        .main-nav{
            width: 800px;
            margin: 10px auto;
        }
        .main-nav li{
            display: inline;
        }
        .first-nav{
            padding-left: 0px;
        }
        .pull-right {
            float: right;
        }
        .pull-left{
            float:left;
        }
        .col-primary{
            width: 85%;
        }
        .col-sidebar{
            padding-top: 20px;
            width: 15%;
        }
        .clearfix{
            clear: both;
        }
        button.buy-btn {
            border: 1px solid #DA5B00 !important;
            background: #DA5B00 !important;
        }
        button.buy-btn .ui-button-text{
            color:#FFFFFF;
        }
        .ui-widget-header{
            border: 1px solid #FFFFFF !important;
            background: #FFFFFF !important;
        }
        {% block style%}


        {% endblock style%}

    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--QUANDO FOR USAR BOOTSTRAP NAO EH PRA USAR ESSA CARAIA DE CLASSE PROPRIA!!! ISSO EH SO PRA TESTE!-->
<nav class="main-nav">
    <ul class="pull-left first-nav">
        <li><a href="{% url 'dashboard' %}">Digital Marketplace</a> </li>
    </ul>
    <ul class="pull-right">
        <li><a href="{% url 'products:list' %}">Products</a> </li>
        <li><a href="{% url 'tags:list' %}">Tags</a> </li>
        <li><a href="{% url 'library' %}">Library</a> </li>
        <li><a href="/admin/">Admin Page</a></li>
        <li><a href="/seller/">Seller</a></li>
    </ul>
</nav>
<div class="main-content">
    {% block content %}
    <p>This is Awesome!</p>
    {% endblock content %}
</div>
{%block jquery%}

{% endblock jquery %}

</body>
</html>