src/sellers/urls.py
from django.conf.urls import url

from products.views import (
    ProductCreateView,
    SellerProductListView,
    ProductUpdateView,
)

from .views import (
    SellerDashboard,
    SellerTransactionListView,
    SellerProductDetailRedirectView,
)

app_name = 'sellers'

urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transaction/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^product/add/$', ProductCreateView.as_view(), name="product_create"),
    url(r'^product/$', SellerProductListView.as_view(), name="product_list"),
    url(r'^product/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^product/(?P<pk>\d+)/$', SellerProductDetailRedirectView.as_view()),
]

src/tags/urls.py
from django.conf.urls import url

from .views import (
    TagListView,
    TagDetailView
    )

app_name = 'tags'
urlpatterns = [
    url(r'^detail/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
    url(r'^list/$', TagListView.as_view(), name='list'),
]

src/billing/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

from products.models import Product


class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # se quiser, estudar sobre generic foreign keys (deixa escolher qualquer model + id pra associar.)
    # e nao uma em especifico como abaixo
    product = models.ForeignKey(Product)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=9.99, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    success = models.BooleanField(default=True)
    # transaction_id_payment_system = Braintree / Stripe / PayPal / PagSeguro ...
    # payment_method
    # last_four

    @python_2_unicode_compatible
    def __str__(self):
        return str(self.id)

src/sellers/models.py
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.core.urlresolvers import reverse

# Create your models here.


# simples. Se for approved, pode vender
class SellerAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_seller", blank=True)
    active = models.BooleanField(default=False)
    # auto_now_add = salva a hora no momento q foi criado
    # auto_now = salva a hora toda vez que atualizar esta entrada no banco
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    @python_2_unicode_compatible
    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("products:vendor_detail", kwargs={"vendor_name": self.user.username})

src/sellers/forms.py
from django import forms


# TODO: BUG: se o usuario nao marcar a checkbox abaixo e der submit, da pau
class NewSellerForm(forms.Form):
    agree = forms.BooleanField(label='Agree to Terms', widget= forms.CheckboxInput)

src/dashboard/views.py
import random
from django.views.generic import View
from django.shortcuts import render
from products.models import Product, CuratedProducts
# Create your views here.


class DashBoardView(View):

    def get(self, request, *args, **kwargs):
        # get the views for the requested user:
        # assuming that user is not logged in
        tag_views = None
        top_tags = None
        products = None
        owned = None
        curated = CuratedProducts.objects.filter(active=True).order_by("?")
        try:
            # tagview_set -> tem que usar _set  pq eh foreign key
            tag_views = request.user.tagview_set.all().order_by("-count")[:5]
        except:
            pass
        try:
            # myproducts.products -> tem que usar . pq eh OneToOneField
            owned = request.user.myproducts.products.all()
        except:
            pass

        if tag_views:
            top_tags = [x.tag for x in tag_views]
            # \ :allows to add aditional things to the calls (allows to continue adding at the bottom line)
            products = Product.objects.filter(tag__in=top_tags)
            if owned:
                products = products.exclude(pk__in=owned)
            # checking if the number of clicks on a determined tag is less than some number
            # if yes, just show the user a bunch of random products (mais uma vez outra solucao porca)
            if products.count() < 10:
                products = Product.objects.all().order_by("?")
                if owned:
                    products = products.exclude(pk__in=owned)
                products = products[:10]
            else:
                products = products.distinct()
                # giving a list of randomized products. Website becomes more dynamic
                products = sorted(products, key= lambda x: random.random())

        context = {
            "products": products,
            "top_tags": top_tags,
            "curated": curated,
        }

        return render(request, "dashboard/view.html", context)

src/sellers/views.py
from django.shortcuts import render
from django.views.generic import View

# Create your views here.

from digitalmarket.mixins import LoginRequiredMixin
from .mixins import SellerAccountMixin
from .forms import NewSellerForm
from .models import SellerAccount
from django.views.generic.edit import FormMixin
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.shortcuts import get_object_or_404

from billing.models import Transaction
from products.models import Product


class SellerProductDetailRedirectView(RedirectView):

    permanent = True
    # query_string = True
    # pattern_name = 'article-detail'

    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()


class SellerTransactionListView(SellerAccountMixin, ListView):
    model = Transaction
    template_name = 'sellers/transaction_list_view.html'

    def get_queryset(self):
        return self.get_transactions()
        # account = SellerAccount.objects.filter(user=self.request.user)
        # if account.exists():
        #     products = Product.objects.filter(seller=account)
        #     return Transaction.objects.filter(product__in=products)
        # return []


class SellerDashboard(SellerAccountMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = "/seller/"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        # one way to get the form
        # apply_form = NewSellerForm()
        # since we have FormMixin we can use this way:
        apply_form = self.get_form()
        # with mixin
        account = self.get_account()
        # without mixin
        # account = SellerAccount.objects.filter(user=self.request.user)
        # exists = account.exists()
        context = {}
        if not account:
            context['title'] = "Apply for an account"
            context['apply_form'] = apply_form
        else:
            # without mixin
            # account = account.first()
            active = account.active
            context['active'] = active
            context['account'] = account
            if active:
                context['title'] = "Dashboard"


                # with mixin
                context['products'] = self.get_products()

                transactions = self.get_transactions()
                transactions_today = self.get_transactions_today(transactions)

                context['transactions_today'] = transactions_today
                context['today_sales'] = self.get_today_sales(transactions)
                context['total_sales'] = self.get_total_sales()
                context['transactions'] = transactions.exclude(pk__in=transactions_today)[:10]

                # without mixin
                # products = Product.objects.filter(seller=account)
                # context['products'] = products
                # context['transactions'] = Transaction.objects.filter(product__in=products)[:10]
            else:
                context['title'] = "Account Pending"

        return render(request, "sellers/dashboard.html", context)

    def form_valid(self, form):
        valid_data = super(SellerDashboard, self).form_valid(form)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data

src/sellers/templates/sellers/dashboard.html
{% extends "base.html" %}

{% block content %}
<h1>{{title}}</h1>

{% if apply_form %}
<form method="POST" action=''>
    {% csrf_token %}
    <h3>Rules of the MarketPlace</h3>
    <ol>
        <li>Be kind</li>
        <li>Sell well</li>
        <li>Don't steal</li>
    </ol>
    {{apply_form.as_p}}
    <br/>
    <input type="submit"/>
</form>
{% endif %}

{% if products %}
<div class="pull-right col-sidebar">
    <p>VER O PORQUE QUANDO EU EDITO UM ITEM, MANDA PRO FIM DESTA LISTA!!!!</p>
    <h4>My Products
        <small>
            <br/>
            <a href="{% url 'sellers:product_create' %}">Add</a> | <a href="{% url 'sellers:product_list' %}">View All</a>
        </small>
    </h4>
{% include 'products/product_list_snippet.html' with product_list=products %}
</div>
{% endif %}


{% if transactions_today %}
<div class="pull-left col-primary">
    <h3>Today's Sales are ${{ today_sales }}</h3>
{% include 'sellers/transaction_list.html' with transaction_list=transactions_today %}
</div>

{% else %}
<p>No recent transactions</p>
{% endif %}

{% if transactions %}
<br/>
<div class="pull-left col-primary">
    <h3>Recent Transaction History (Total Sales: ${{ total_sales }})</h3>
{% include 'sellers/transaction_list.html' with transaction_list=transactions %}
</div>

<p>
    <a href="{% url 'sellers:transactions' %}">View all transactions</a>
</p>

{% endif %}

{% endblock content %}

src/sellers/templates/sellers/product_list_view.html
{% extends "base.html"%}
{% load get_thumbnail %}
{% block style%}

{% endblock style%}

{% block content %}

<h1>My Seller Product</h1>
<p>
<form>
    <input type="text" name="q" placeholder="Search" value="{{ request.GET.q }}"/>
    <input type="submit" value="Search"/>
</form>
</p>
<table>
    {% for instance in product_list %}
    {% with instance|get_thumbnail:"micro" as thumb %}
    <tr class="">
        <td>
            {{instance.id}}
        </td>
        <td>
            <a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a>
        </td>
        <td>
        {% if thumb %}
        <a href="{{ instance.get_absolute_url }}">
            <img src='{{ thumb }}'></a><br/>
        {% endif %}
        </td>
        <td>{{ instance.price }}</td>
        <td><a href="{{instance.get_edit_url}}">Edit</a> | <a href="#">Delete</a></td>
    </tr>
    {% endwith %}
    {% empty %}
    <li> No products yet.</li>
    {% endfor %}
</table>


{% endblock content %}

src/sellers/templates/sellers/transaction_list.html
<table>
    <thead>
        <th>Product</th>
        <th>User</th>
        <th>Price</th>
        <th>Time</th>
    </thead>
    <tbody>
        {% for trans in transaction_list %}
        <tr>
            <td>{{trans.product}}</td>
            <td>{{trans.user}}</td>
            <td>{{trans.price}}</td>
            <!--Using template filter timesince-->
            <td>{{trans.timestamp | timesince}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

src/sellers/templates/sellers/transaction_list_view.html
{% extends "base.html"%}

{% block style%}
.row1{
    background-color:#EEEEEE;
}
.row2{
    background-color:#DDDDDD;
}

{% endblock style%}

{% block content %}

<h1>Transactions</h1>

<ul>
    {% include 'sellers/transaction_list.html' with transaction_list=object_list %}

</ul>


{% endblock content %}