src/products/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from .views import (
    ProductCreateView,
    ProductDetailView,
    ProductDownloadView,
    ProductListView,
    ProductUpdateView,
    ProductRatingAjaxView,
    VendorListView
    )

app_name = 'products'
urlpatterns = [
    # url(r'^$', views.detail_view, name='detail_view'),
    # ex: /product/detail/5
    # \d+ only digits
    # parameter name = object_id
    # .* everything
    # url(r'^create/$', views.create_view, name='create_view'),
    # url(r'^detail/(?P<object_id>\d+)/$', views.detail_view, name='detail_view'),
    # url(r'^detail/(?P<slug>[\w-]+)/$', views.detail_slug_view, name='detail_slug_view'),
    # url(r'^detail/(?P<object_id>\d+)/edit/$', views.update_view, name='update_view'),
    url(r'^list/$', ProductListView.as_view(), name='list'),
    # vendor_name eh passado como **kwargs
    url(r'^vendor/$', RedirectView.as_view(pattern_name='products:list'), name='vendor_list'),
    url(r'^vendor/(?P<vendor_name>[\w.@+-]+)/$', VendorListView.as_view(), name='vendor_detail'),

    url(r'^detail/(?P<pk>\d+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^detail/(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail_slug'),

    url(r'^(?P<pk>\d+)/download/$', ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/$', ProductDownloadView.as_view(), name='download_slug'),

    url(r'^detail/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='update'),
    url(r'^detail/(?P<slug>[\w-]+)/edit/$', ProductUpdateView.as_view(), name='update_slug'),

    url(r'^ajax/rating/$', ProductRatingAjaxView.as_view(), name='ajax_rating'),


]

src/tags/urls.py
from django.conf.urls import url

from .views import (
    TagListView,
    TagDetailView
    )

app_name = 'tags'
urlpatterns = [
    url(r'^detail/(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
    url(r'^list/$', TagListView.as_view(), name='list'),
]

src/billing/models.py
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.

from products.models import Product


class Transaction(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # se quiser, estudar sobre generic foreign keys (deixa escolher qualquer model + id pra associar.)
    # e nao uma em especifico como abaixo
    product = models.ForeignKey(Product)
    price = models.DecimalField(max_digits=100, decimal_places=2, default=9.99, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    success = models.BooleanField(default=True)
    # transaction_id_payment_system = Braintree / Stripe / PayPal / PagSeguro ...
    # payment_method
    # last_four

    @python_2_unicode_compatible
    def __str__(self):
        return str(self.id)

src/products/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify

# Generate unique slugs
from random import shuffle, choice, randint
import string

# put foreign key equal to the default django user model
from django.conf import settings

# Library for get_absolute_url
from django.core.urlresolvers import reverse
# Reverse: Takes an URL name or View name and makes it more dynamic

# ================================================================
# __str__ -> python 3.x
# __unicode__ -> python 2.x
# in order to use __str__ and be compatible import:
from django.utils.encoding import python_2_unicode_compatible
# and use @python_2_unicode_compatible on top of __str__ function.
# ================================================================

# ------------------ FILE PROTECTION ------------------
from django.core.files.storage import FileSystemStorage
# -----------------------------------------------------

# ------------------- THUMBNAIL GENERATION LIBRARIES -------------------
import os
import random
import shutil
from PIL import Image

from django.core.files import File
# ----------------------------------------------------------------------
# Models
from sellers.models import SellerAccount


# handles the upload process
def download_media_location(instance, filename):
    return "%s/%s" % (instance.slug, filename)

"""
How to dump your data.
-> to have a clean migration
-> do not lose data if you have to destroy your database.
Syntax:
python manage.py dumpdata APP --format json --indent 4 > filename.json
Ex:
python manage.py dumpdata products --format json --indent 4 > products_backup.json

Return the dumped data.
Syntax:
python manage.py loaddata filename.json
Ex:
python manage.py loaddata products_backup.json
"""


class Product(models.Model):
    seller = models.ForeignKey(SellerAccount)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL)
    # n to n database relationship
    # managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="managers_products", blank=True)
    media = models.ImageField(blank=True,
                             null=True,
                             upload_to=download_media_location,
                             storage=FileSystemStorage(location=settings.PROTECTED_ROOT)
                             )
    title = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, unique=True, max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=100,decimal_places=2,default=9.99)
    sale_active = models.BooleanField(default=False)
    sale_price = models.DecimalField(max_digits=100,decimal_places=2,default=6.99,null=True,blank=True)

    @python_2_unicode_compatible
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        view_name = "products:detail_slug"
        return reverse(view_name, kwargs={"slug": self.slug})

    def get_edit_url(self):
        view_name = "sellers:product_edit"
        return reverse(view_name, kwargs={"pk": self.id})

    def get_download(self):
        view_name = "products:download_slug"
        url = reverse(view_name, kwargs={"slug": self.slug})
        return url

    # @property transforma esse metodo em uma property da classe, um atributo. ou seja, nao precisa mais
    # chamar como product_object.get_price(). Agora pode-se chamar como product_object.get_price
    # como se fosse um product_object.slug ou .title
    @property
    def get_price(self):
        if self.sale_price and self.sale_active:
            return self.sale_price
        return self.price

    def get_html_price(self):
        price = self.get_price
        if price == self.sale_price:
            # podia trocar sale_price mt bem por price...
            return "<p><span>%s</span>  <span style='color:red; text-decoration:line-through'>%s</span></p>" %(self.sale_price, self.price)
        else:
            return "<p>%s</p>" % self.price

    """
    get thumbnails -> instance.thumbnail_set.all() => because thumbnail has a foreign key to Product
    """


# make sure that the product does not already exists
def create_slug(instance):
    # LEMBRAR DE TESTAR ESCAPE STRING POR SEGURANCA DO BANCO!!!!
    # VER SE A DESCRICAO COMECAR COM ' OU " NAO VAI DAR PAU NO BANCO E INJETAR CODIGO MALICIOSO

    # TESTAR O WHILE LOOP PRA VER SE NAO VAI DAR PAU NESSA PORRA!!!

    pre_slug = instance.description[:15].split(" ")
    shuffle(pre_slug)
    pre_slug = ' '.join(pre_slug)
    slug = slugify(instance.title[:42]+" " + pre_slug)
    qs = Product.objects.filter(slug=slug).exists()
    if qs:
        pre_slug = instance.description[:15].split(" ")
        shuffle(pre_slug)
        rnd = [choice(string.ascii_letters + string.digits) for n in range(7)]
        shuffle(rnd)
        rnd = ''.join(rnd)
        pre_slug = ' '.join(pre_slug)+" "+rnd
        slug = slugify(instance.title[:30] + " " + pre_slug)
        while True:
            qs = Product.objects.filter(slug=slug).exists()
            if qs:
                slug += "-" + str(randint(0, 2000000))
            else:
                break
    return slug


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)


# tentando atualizar tabela myProducts automaticamente
def product_update_myproducts_post_save_receiver(sender, instance, *args, **kwargs):
    # cada usuario eh unico. por isso que eu chamo o metodo abaixo com [0] no final.. ja que vai retornar
    # uma query so.
    # todo: verificar se nao e necessario fazer verificacao se caso a query nao retorne nada
    # nota ao To do acima. Acho que nao e necessario. pois so cria-se um produto se ja existe um usuario.
    # todo: talvez criar trigger no banco seja mais rapido... na verdade eh. MUDAR ISSO PRA TRIGGER NO BANCO!!!!
    myproducts = MyProducts.objects.get_or_create(user=instance.seller.user)[0]
    myproducts.products.add(instance)
    myproducts.save()

post_save.connect(product_update_myproducts_post_save_receiver, sender=Product)


def thumbnail_location(instance, filename):
    return "%s/%s" % (instance.product.slug, filename)

THUMB_CHOICES= (
    ("hd", "HD"),
    ("sd", "SD"),
    ("micro", "Micro"),
)


class Thumbnail(models.Model):
    product = models.ForeignKey(Product)
    type = models.CharField(max_length=20, choices=THUMB_CHOICES, default='hd')
    width = models.CharField(max_length=20, null=True, blank=True)
    heigth = models.CharField(max_length=20, null=True, blank=True)
    media = models.ImageField(
            width_field = "width",
            height_field = "heigth",
            blank=True,
            null=True,
            upload_to=thumbnail_location,
            )

    @python_2_unicode_compatible
    def __str__(self):
        return str(self.media.path)


def create_new_thumb(media_path, instance, owner_slug, max_heigth, max_width):
    # path + filename
    filename = os.path.basename(media_path)
    thumb = Image.open(media_path)
    size = (max_heigth, max_width)
    thumb.thumbnail(size, Image.ANTIALIAS)
    temp_loc = "%s/%s/tmp" % (settings.MEDIA_ROOT, owner_slug)
    if not os.path.exists(temp_loc):
        os.makedirs(temp_loc)
    temp_file_path = os.path.join(temp_loc, filename)
    # atencao! solucao meio porca
    if os.path.exists(temp_file_path):
        temp_path = os.path.join(temp_loc, "%s" % random.random(), filename)
        os.makedirs(temp_path)
        temp_file_path = os.path.join(temp_path, filename)

    temp_image = open(temp_file_path, "w")
    thumb.save(temp_file_path)
    thumb_data = open(temp_file_path, "rb")

    thumb_file = File(thumb_data)
    instance.media.save(filename, thumb_file)
    temp_image.close()
    thumb_data.close()
    shutil.rmtree(temp_loc, ignore_errors=True)
    return


def product_post_save_receiver(sender, instance, created, *args, **kwargs):
    if instance.media:
        # get or create instance
        hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
        sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
        micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

        hd_max = (400, 400)
        sd_max = (200, 200)
        micro_max = (50, 50)
        media_path = instance.media.path
        owner_slug = instance.slug
        if hd_created:
            create_new_thumb(media_path, hd, owner_slug, hd_max[0], hd_max[1])
        if sd_created:
            create_new_thumb(media_path, sd, owner_slug, sd_max[0], sd_max[1])
        if micro_created:
            create_new_thumb(media_path, micro, owner_slug, micro_max[0], micro_max[1])


post_save.connect(product_post_save_receiver, sender=Product)


class MyProducts(models.Model):
    # user tem relacao OneToOne. pode usar entao dot notation pra acessar elementos
    #
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    products = models.ManyToManyField(Product, blank=True)

    @python_2_unicode_compatible
    def __str__(self):
        return "%s : %s product(s)" %(self.user, self.products.count())

    class Meta:
        verbose_name = "My Products"


class ProductRating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    products = models.ForeignKey(Product, blank=True)
    rating = models.IntegerField(null=True, blank=True)
    verified = models.BooleanField(default=False)

    @python_2_unicode_compatible
    def __str__(self):
        return "%s" % self.rating


class CuratedProducts(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    section_name = models.CharField(max_length=120)
    products = models.ManyToManyField(Product, blank=True)
    active = models.BooleanField(default=True)

    @python_2_unicode_compatible
    def __str__(self):

src/products/forms.py
from django import forms

from .models import Product
from django.utils.text import slugify
PUBLISH_CHOICES = (
    ('publish', "Publish"),
    ('draft', "Draft"),
)


# Hard way to create Forms
class ProductAddForm(forms.Form):
    title = forms.CharField(label='Label changing test (Title)', widget=forms.TextInput(
            attrs={
                "class": "my-custom-class",
                "placeholder": "Product Title",
            }
    ))
    description = forms.CharField(widget=forms.Textarea(
        attrs={"class": "my-custom-class",
               "placeholder": "Put the description here.",

               }
    ))
    price = forms.DecimalField(widget=forms.NumberInput(
        attrs={
            "class": "my-custom-class",
            "placeholder": "Product Price"
        }
    ))
    publish = forms.ChoiceField(widget=forms.RadioSelect, choices=PUBLISH_CHOICES, required=False)

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price <= 1.00:
            raise forms.ValidationError("Price must be greater than $1")
        elif price >= 100.00:
            raise forms.ValidationError("Price must be less than $100")
        return price

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) > 3:
            return title
        else:
            raise forms.ValidationError("Title must be greater than 3 characters long.")


# Easy way to create forms
class ProductModelForm(forms.ModelForm):
    tags = forms.CharField(label='Related Tags', required=False)
    publish = forms.ChoiceField(widget=forms.RadioSelect, choices=PUBLISH_CHOICES, required=False)

    class Meta:
        model = Product
        fields = [
            "title",
            "description",
            "price",
            "media",
        ]
        widgets = {
            "title": forms.TextInput(attrs={
                "class": "my-custom-class",
                "placeholder": "Product Title",}),
            "description": forms.Textarea(attrs={
                "class": "my-custom-class",
                "placeholder": "Put the description here."}),
        }

    # We are going to override the clean method in order to make validations
    #def clean(self, *args, **kwargs):
        # run the default clean method
        #cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
        #title = cleaned_data.get("title")
        #slug = slugify(title)
        #qs = Product.objects.filter(slug=slug).exists()
        #if qs:
        #    raise forms.ValidationError("Title is taken. A new title is needed. Please try again.")
        #return cleaned_data

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price <= 0:
            raise forms.ValidationError("Price must be greater than $0")
        return price

    def clean_title(self):
        title = self.cleaned_data.get("title")
        if len(title) > 3:
            return title
        else:
            raise forms.ValidationError("Title must be greater than 3 characters long.")

src/products/templates/products/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <style>

        {% block style%}


        {% endblock style%}

    </style>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block content%}
<p>This is Awesome!</p>
{%endblock content%}
</body>
</html>

src/products/templates/products/detail_view.html
{% extends "base.html" %}

{%block style%}
h1{
    color: green;
}
{%endblock style%}


{% block content%}
<h1> Product: {{object.title}}</h1>
<p> {{ object.description }}</p>
<p> {{ object.price }}</p>

{% endblock content%}

src/products/templates/products/form.html
{% extends "base.html" %}

{% block content %}
{% include "products/form_include.html" with form=form submit_btn=submit_btn %}

{% endblock content %}

src/products/templates/products/form_include.html
<form method="POST" action="" enctype="multipart/form-data">
    <!--esse enctype acima eh muito importante quando queremos dar upload em arquivos-->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' />
</form>

src/products/templates/products/library_list.html
{% extends "base.html"%}
{% load get_thumbnail %}
{% block style%}
.row1{
    background-color:#EEEEEE;
}
.row2{
    background-color:#DDDDDD;
}

{% endblock style%}

{% block content %}

<h1>My Library</h1>
<p>
<form>
    <input type="text" name="q" placeholder="Search" value="{{ request.GET.q }}"/>
    <input type="submit" value="Search"/>
</form>
</p>
<table class="table">
    <thead>
        <tr>
        <th>Product</th>
        <th>Image</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
    <!--TODO: IF YOU TRY TO RATE WITHOUT BEING LOGGED IN, GO TO THE LOGIN PAGE-->
    {% for instance in product_list %}
    {% with instance|get_thumbnail:"micro" as thumb %}
    <tr>
    <td><a href="{{ instance.get_absolute_url }}">{{ instance }} </a></td>
    <td>
        {% if thumb %}
        <a href="{{ instance.get_absolute_url }}"><img src='{{ thumb }}'></a><br/>
        {% endif %}
    </td>
    <td>
        <!-- TODO: Mesmo que nao tenha media, ainda retorna o download link e da pau-->
        {% if instance.get_download %}
        <a href="{{ instance.get_download }}">Download</a>
        {% else %}
        <span>Comming Soon.</span>
        {% endif %}
    </td>
    </tr>
    {% endwith %}
    {% empty %}
    <li> No products in library yet. Please, shop now.</li>
    {% endfor %}
    </tbody>
</table>


{% endblock content %}

src/products/templates/products/list_view.html
{% extends "base.html" %}
{% block content%}
<h1>MARILENE</h1>


{{queryset}}


{{block.super}}
{% endblock content%}

src/products/templates/products/product_detail.html
{% extends "base.html" %}
<style>
{%block style%}
h1{
    color: green;
}

.rating {
    float:left;
    width: 200px;
}

/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
   follow these rules. Every browser that supports :checked also supports :not(), so
   it doesn’t make the test unnecessarily selective */
.rating:not(:checked) > input {
    position:absolute;
    top:-9999px;
    clip:rect(0,0,0,0);
}

.rating:not(:checked) > label {
    float:right;
    width:1em;
    padding:0 .1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:200%;
    line-height:1.2;
    color:#ddd;
    text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:before {
    /*content: '★ ';
    content: '☺ ';
    */
    content: '♥  ';
}

.rating > input:checked ~ label {
    color: #f70;
    text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);
}

.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
    color: gold;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > input:checked + label:hover,
.rating > input:checked + label:hover ~ label,
.rating > input:checked ~ label:hover,
.rating > input:checked ~ label:hover ~ label,
.rating > label:hover ~ input:checked ~ label {
    color: #ea0;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}

.rating > label:active {
    position:relative;
    top:2px;
    left:2px;
}

{%endblock style%}
</style>

{% block jquery %}
<script>
    //only runs after the document is ready
    $(document).ready(function(){

        $(".rating input[value='{{my_rating}}']").attr("checked", "checked");

       $(".rating input[type='radio']").click(function(event){
            //var inputValue = $(this).val();
            //console.log(inputValue);
            var request = $.ajax({

                    method:"POST",
                    url: "{% url 'products:ajax_rating' %}",
                    data: {
                        product_id: "{{object.id}}",
                        rating_value: $(this).val()
                    }
                });
                request.done(function(data){

                });
                request.fail(function(jqXHR, textStatus) {
                    if(jqXHR.status == 404){
                        alert("Page not found!");
                    }else if(jqXHR.status == 401){
                        alert("You need to be logged in in order to purchase something.");
                    }else{
                        alert("There was an error with your request. Please try again.");
                    }
                });
        });


       //.click if the item is touched or clicked, runs the function
       $("#purchase-btn").click(function(event){
           var purchaseBtn = $(this);
           // impede que o padrao do elemento aconteca.. se for um link, nao leva a lugar nenhum
           event.preventDefault();
           $("#dialog-confirm").fadeIn("300").dialog({
               resizable:false,
               height:350,
               width:350,
               modal:true,
               buttons:{
                   1: {
                       id: "close",
                       text: "Confirm",
                       click: function () {
                           //console.log("confirm");
                           var request = $.ajax({
                                method:"POST",
                                url: "{% url 'checkout' %}",
                                data: {
                                    product_id: "{{object.id}}"
                                }
                            });
                            request.done(function(data){
                                if("{{object.media}}"){
                                    // put the star rating system together with the download links
                                    purchaseBtn.before(
                                        "<p><a href='"+data.download+"'>Download</a></p><p><a href='"+data.preview+"'>Preview</a></p>" +
                                        "<p> <strong>My Rating</strong>" +
                                        "<div class='rating'>" +
                                        "<input type='radio' id='star5' name='rating' value='5'/><label for='star5' title='Rocks!'>&nbsp;5 stars</label>" +
                                        "<input type='radio' id='star4' name='rating' value='4'/><label for='star4' title='Pretty Good'>&nbsp;4 stars</label>" +
                                        "<input type='radio' id='star3' name='rating' value='3'/><label for='star3' title='Meh'>&nbsp;3 stars</label>" +
                                        "<input type='radio' id='star2' name='rating' value='2'/><label for='star2' title='Kinda bad'>&nbsp;2 stars</label>" +
                                        "<input type='radio' id='star1' name='rating' value='1'/><label for='star1' title='Sucks big time'>&nbsp;1 stars</label>" +
                                        "</div>" +
                                        "</p>"

                                );
                                }else{
                                    purchaseBtn.before(
                                      "<p>Product is coming soon for Download</p>"
                                    );
                                }

                                purchaseBtn.fadeOut(11);
                            });
                            request.fail(function(jqXHR, textStatus) {
                                if(jqXHR.status == 404){
                                    alert("Page not found!");
                                }else if(jqXHR.status == 401){
                                    alert("You need to be logged in in order to purchase something.");
                                }else{
                                    alert("There was an error with your request. Please try again.");
                                }
                            });
                           $(this).dialog("close")
                       },
                       class: "buy-btn"
                   },
                   2:{
                       id: "close",
                       text: "Cancel",
                       click: function () {
                           $(this).dialog("close")
                       },
                       class: "cancel-btn"
                   }
               }
           })
       })
    })

</script>
{% endblock jquery %}


{% block content%}
<div class="col-primary pull-left">
    <h1> Product: {{object.title}}</h1>
    <small>Vendedor: <a href="{{ object.seller.get_absolute_url }}">{{ object.seller.user.username }}</a></small>
    <p> {{ object.description }}</p>
    <!--O template filter safe vai criar um safe html-->
    <!--mandei um <p> junto ficando <p> <p> </p> </p>... dai ele remove o <p> de dentro transformando em safe -->
    <p> {{ object.get_html_price|safe }}</p>
        <!--Ficar esperto com esse valor. pode mudar se a transacao nao for valida ou se for dado refund na compra.-->
    <p> Purchases: {{ object.transaction_set.count}}</p>

    <!--FIX: tive que adicionar 3 br's aqui-->
    <br/><br/><br/>
    {% for img in object.thumbnail_set.all %}
        <img src="{{ img.media.url }}" />
    {% endfor %}
</div>
<div class="col-sidebar pull-right">

    {% if request.user.is_authenticated and object in request.user.myproducts.products.all %}
        {% if object.media %}
            <p><a href="{{ object.get_download }}">Download</a></p>
            <p><a href="{{ object.get_download }}?preview=True">Preview</a></p>

        <!--SE EU FOR DONO DO PRODUTO, NAO DEVERIA APARECER AS ESTRELINHAS, MAS A NOTA SIM-->
            {% if is_owner == False %}
          <p>
          <strong>My Rating</strong>
          <div class="rating">
           <input type="radio" id="star5" name="rating" value="5"/><label for="star5" title="Rocks!">&nbsp;5 stars</label>
           <input type="radio" id="star4" name="rating" value="4"/><label for="star4" title="Pretty Good">&nbsp;4 stars</label>
           <input type="radio" id="star3" name="rating" value="3"/><label for="star3" title="Meh">&nbsp;3 stars</label>
           <input type="radio" id="star2" name="rating" value="2"/><label for="star2" title="Kinda bad">&nbsp;2 stars</label>
           <input type="radio" id="star1" name="rating" value="1"/><label for="star1" title="Sucks big time">&nbsp;1 stars</label>
          </div>
            </p>
         {% endif %}
        {% else %}

            <p>Product is coming soon for Download</p>
        {% endif %}
    {% else %}
    <!--
    TODO: LER ABAIXO.
    BUG! se clicar em purchase, logo em seguida ir no preview e voltar a pagina na seta do navegador,
    o botao purchase volta a ativa!
    Possivel solucao. Forcar o recarregamento da pagina apos a compra
    -->
        <p><a id="purchase-btn" href="#">{% if object.media %}Purchase{% else %}Pre-Order{% endif %}</a> </p>

        <div id="dialog-confirm" title="Confirm Purchase" style="display:none">
         <p>Your card on file will be charged after you agree below.</p>
        </div>

    {% endif %}

    {% if rating_avg.rating__avg  %}
    <p> {{ rating_avg.rating__avg }} Average Rating from {{ rating_avg.rating__count }} users.</p>
    {% endif %}
</div>
<div class="clearfix"></div>
{% endblock content%}

src/products/templates/products/product_list.html
{% extends "base.html"%}

{% block style%}
.row1{
    background-color:#EEEEEE;
}
.row2{
    background-color:#DDDDDD;
}

{% endblock style%}

{% block content %}

<h1>{% if vendor_name %}{{vendor_name}}{% endif %} Products</h1>
<p>
<form>
    <input type="text" name="q" placeholder="Search" value="{{ request.GET.q }}"/>
    <input type="submit" value="Search"/>
</form>
</p>
<ul>
    {% include "products/product_list_snippet.html" with product_list=object_list %}


    <!--exemplo de uso de cycle para colocar classes diferentes em momentos alternados a cada laco do for-->
    <!--{% for instance in object_list %}-->
        <!--<li class="{% cycle 'row1' 'row2' %}">-->
            <!--<a href="{{ instance.get_absolute_url }}">{{ instance }} </a><br/>-->
            <!--{{ instance.description|truncatechars:50 }}<br/>-->
            <!--{{ instance.price }}-->
        <!--</li>-->
    <!--{% empty %}-->
        <!--<li> No products yet.</li>-->
    <!--{% endfor %}-->
</ul>


{% endblock content %}

src/products/templates/products/product_list_snippet.html
{% load get_thumbnail %}


{% for instance in product_list %}
{% with instance|get_thumbnail:"micro" as thumb %}
<li>
    <a href="{{ instance.get_absolute_url }}">{{ instance }} </a><br/>
    {% if thumb %}
    <a href="{{ instance.get_absolute_url }}"><img src='{{ thumb }}'></a><br/>
    {% endif %}
    {{ instance.get_html_price|safe }}
</li>
{% endwith %}
{% empty %}
<li> No products yet.</li>
{% endfor %}